openapi: 3.0.0

info:
  description: API specification
  version: 0.0.1
  title: Message API specification

servers:
  - url: http://localhost:3000/

paths:
  /users/sessions/github:
    get:
      description: Redirect to authentication service with Github
      tags:
        - Users

  /users/sessions/callback:
    get:
      description: Handle authentication callback
      tags:
        - Users
      responses:
        201:
          description: User data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /users/{id}:
    patch:
      description: User update
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          description: User id
          schema:
            type: string
      security:
        - bearerAuth: []
      requestBody:
        description: Avatar, bio or name can be updated
        content:
          application/json:
            schema:
              type: object
              properties:
                avatar:
                  type: string
                bio:
                  type: string
                name:
                  type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

    delete:
      description: User deletion
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          description: User id
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        204:
          description: Successful response

  /users/contacts:
    delete:
      description: Removing user from contacts
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          description: Contact id
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        204:
          description: Successful response

  /invitations:
    post:
      description: Invitation creation
      tags:
        - Invitations
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                senderId:
                  type: string
                  required: true
                recipientId:
                  type: string
                  required: true
                content:
                  type: string
                  required: true
      responses:
        201:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  senderId:
                    type: string
                  recipientId:
                    type: string
                  createdAt:
                    type: string
                  content:
                    type: string

  /invitations/{senderId}:
    post:
      description: Invitation acceptance
      tags:
        - Invitations
      parameters:
        - name: senderId
          in: path
          description: Sender user ID
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        201:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  user1_id:
                    type: string
                  user2_id:
                    type: string

    delete:
      description: Invitation rejection
      tags:
        - Invitations
      parameters:
        - name: senderId
          in: path
          description: Sender user ID
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        204:
          description: Successful response

  /groups:
    post:
      description: Group creation
      tags:
        - Groups
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  required: true
      responses:
        201:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'

  /groups/{id}:
    delete:
      description: Group deletion
      tags:
        - Groups
      parameters:
        - name: id
          in: path
          description: Group ID
          required: true
      security:
        - bearerAuth: []
      responses:
        204:
          description: Successful response

    patch:
      description: Group update
      tags:
        - Groups
      parameters:
        - name: id
          in: path
          description: Group ID
          required: true
      security:
        - bearerAuth: []
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'

  /groups/{groupId}/members:
    post:
      description: Adding member to the group
      tags:
        - GroupMembers
      parameters:
        - name: groupId
          in: path
          description: Group ID
          required: true
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  required: true
      responses:
        201:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupMember'

  /groups/{groupId}/members/{id}:
    delete:
      description: Removing member to the group
      tags:
        - GroupMembers
      parameters:
        - name: groupId
          in: path
          description: Group ID
          required: true
        - name: id
          in: path
          required: true
          description: Member ID
      security:
        - bearerAuth: []
      responses:
        204:
          description: Successful response

  /groups/{groupId}/members/leave:
    delete:
      description: Leave the group
      tags:
        - GroupMembers
      parameters:
        - name: groupId
          in: path
          description: Group ID
          required: true
      security:
        - bearerAuth: []
      responses:
        204:
          description: Success response

  /groups/{groupId}/members/transfer:
    patch:
      description: Group administration transfer
      tags:
        - GroupMembers
      parameters:
        - name: groupId
          in: path
          required: true
          description: Group ID
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                memberId:
                  type: string
                  required: true
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupMember'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        avatar:
          type: string
        bio:
          type: string
        name:
          type: string
        email:
          type: string
        provider:
          type: string

    Group:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        cover:
          type: string
        groupMembers:
          type: array

    GroupMember:
      type: object
      properties:
        id:
          type: string
        group_id:
          type: string
        user_id:
          type: string
        role:
          type: string
